# Generated by Django 4.2.1 on 2023-06-02 01:24

from django.db import migrations


class Migration(migrations.Migration):
    def forwards_func(self, schema_editor):
        Chain = self.get_model("chains", "Chain")
        ChainNode = self.get_model("chains", "ChainNode")
        for chain in Chain.objects.all():
            ChainNode.objects.filter(root_id=chain.root_id).update(chain_id=chain.id)
            ChainNode.objects.filter(id=chain.root_id).update(chain_id=chain.id)

    dependencies = [
        ("chains", "0002_updates_for_chain_editor"),
    ]

    operations = [migrations.RunPython(forwards_func)]
